DROP TABLE IF EXISTS PLAYER;

CREATE TABLE PLAYER (
		PLAYER_CODE VARCHAR(10) NOT NULL PRIMARY KEY
	, 	FIRST_NAME VARCHAR(30)
	, 	LAST_NAME VARCHAR(30)
	, 	CLUB VARCHAR(30)
	,	RANK INT
	, 	PRIMARY KEY (PLAYER_CODE)
);


